### ISSUE TITLE
Config.plist and ConfigDW1560.plist might be swapped

### ISSUE THREAD

**Issue by javierlori** [extric99/Hackintosh-NUC7I7DNKE#1]
I think that you have swapped the names of both config.plist in your latest release. Config.plist has the kexts for DW1560 (Bcrm*kext, etc.) and the configDw1560.plist has the Intel kexts.
Anyway thank you for your hardwork and keep it up.
Best Regards,
RLJ63 (from tonyMacx86 Nuc Thread)

**Comment by extric99** [comment]
Thanks for the feedback! I published a new release with OpenCore 0.6.3 which should have again the correct mapping.
