### ISSUE TITLE
[BUG] Dual Monitors

### ISSUE THREAD

**Issue by Malumen** [extric99/Hackintosh-NUC7I7DNKE#5]
Hi @extric99

Been using your efi for a while now. Everything works great! I've even switched to using the OpenIntelWireless project and currently using the Airportitlwm stable v1.3 and it works beautifully.

I want to use it with two monitors now, but I can't get it to work properly with 2 monitors.

Can you share your BIOS settings? Is your iGPU properly patched?

**Comment by extric99** [comment]
I never tried dual monitors myself but it should work fine
Check with hackintool if your setup has the same igpu and framebuffer as i have on the readme. If this is the case the patch is applied correctly.
I am using the default bios settings myself as explained on the readme
You dont mention any details on the issue or bios version you are having so i can not really help either.

**Comment by Malumen** [comment]
> I never tried dual monitors myself but it should work fine
> Check with hackintool if your setup has the same igpu and framebuffer as i have on the readme. If this is the case the patch is applied correctly.
> I am using the default bios settings myself as explained on the readme
> You dont mention any details on the issue or bios version you are having so i can not really help either.

I have the NUC7i7DN _H_ E (which just has the added height for the 2.5inch drive). Exactly the same unit.

In this case, I think you are missing the Con1 and Con2 fields for the physical ports. I have tried dual monitors and it causes the system to have a black screen (at boot, after Apple logo loading bar). Also, if the system is running and I hot-plug another monitor into it, then both screens go black. In both these scenarios: I cannot recover the system. I need to hard power down and boot the system back up.

Another user an I have been struggling with it over the past few days and got nowhere. Not sure what we are doing wrong to figure out the proper framebuffer settings.

**Comment by extric99** [comment]
Try adding agdpmod=pikera to the boot arguments when tinkering with the iGPU patches.
I had a black screen when I added additional arguments to resolve the audio replug issue but adding agdpmod=pikera resolved it.
