### ISSUE TITLE
Can not get 4k60hz

### ISSUE THREAD

**Issue by kb-hat-tuan** [extric99/Hackintosh-NUC7I7DNKE#7]
@extric99 
Hi,
Thank you for sharing your hard work.
I'm have same NUC and using your EFI, but I can not select 60hz on 4k monitor.
Maximum frame rate of 1080p~4k is 30hz.
Only 720p have 60hz.
My HDMI cable work normal on other PC.

Do you have same problem?

Best regard,
HT

**Comment by kb-hat-tuan** [comment]
I just found that Intel HD 620 only support 4k24hz on HDMI
https://ark.intel.com/content/www/us/en/ark/products/124968/intel-core-i78650u-processor-8m-cache-up-to-4-20-ghz.html
https://github.com/dragonflylee/Yoga-730-hackintosh/issues/21

But in Ubuntu 22.04, I can get 4k60hz.

**Comment by extric99** [comment]
I tested and can can replicate the issue 
On a 1440p monitor i can use 60hz at 1440p
However on a 4k monitor you need to drop down to 720p to get 60hz

Only thing i can think of is to change the framebuffer as suggested in the github thread. Suggest you try this. 
i dont have a lot of time to play with this now so please try test yourself. I will try to look at it later

Technically the NUC supports 4k according to https://ark.intel.com/content/www/us/en/ark/products/130392/intel-nuc-kit-nuc7i7dnke.html as it seems to be using the display port to drive the HDMI. More precisely 
Dual HDMI 2.0a, 4-lane eDP 1.4

Seems the nuc is using the LSPCON controller to drive the HDMI from the DP (see p20) so it should be possible to enable 4k with the correct 
https://www.intel.com/content/dam/support/us/en/documents/mini-pcs/nuc-kits/NUC7i7DN_TechProdSpec.pdf

see 

https://www.tonymacx86.com/threads/an-idiots-guide-to-lilu-and-its-plug-ins.260063/#4K

add "-cdfon" as a MacOS boot argument

add below to the device properties of the graphics adaptor 

                <key>framebuffer-unifiedmem</key>
                <data>
                AAAAgA==
                </data>

**Comment by extric99** [comment]
![image](https://user-images.githubusercontent.com/33332861/191992184-05062528-da5d-4567-b229-09f9bff2e3ea.png)

If you use below it works, Can play 60fps YouTube with no issue 

As framebuffer

			<dict>
                                <key>AAPL,ig-platform-id</key>
				<data>CQClPg==</data>
				<key>AAPL,slot-name</key>
				<string>Internal@0,2,0</string>    
				<key>device-id</key>
				<data>pT4AAA==</data>
				<key>device_type</key>
				<string>VGA compatible controller</string>
				<key>model</key>
				<string>HD Graphics 620</string>
				<key>framebuffer-patch-enable</key>
				<data>AQAAAA==</data>                
                                <key>enable-hdmi-dividers-fix</key>
				<data>AQAAAA==</data>
				<key>enable-hdmi20</key>
				<data>AQAAAA==</data>
				<key>enable-lspcon-support</key>
				<data>AQAAAA==</data>
			</dict>

For the boot arguments

				<key>boot-args</key>
				<string>-cdfon</string>
